//! `fc-app` — the GUI-free project/application model for the FlatCAM Rust port.
//!
//! Rust analogue of FlatCAM's `ObjectCollection` + project persistence
//! (`appMain.py` / `appIO.py`). It models a project as an ordered list of named
//! objects, each with a kind, an optional source file, and a free-form options
//! map (the `LoudDict`/`obj_options` equivalent). Following FlatCAM's approach,
//! geometry is *not* serialized — objects reference their source file and are
//! regenerated by the parser/CAM crates on load, keeping project files small
//! and the model decoupled from the geometry types.
//!
//! Persistence is JSON (`serde`), which is human-readable and forward-compatible
//! via the `version` field.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;

/// Current project-file schema version.
pub const PROJECT_VERSION: u32 = 1;

#[derive(thiserror::Error, Debug)]
pub enum AppError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("object not found: {0}")]
    NotFound(String),
    #[error("compression error: {0}")]
    Compression(String),
}

/// Leading byte of the LZMA (`.lzma` / "alone") container we emit for
/// compressed projects. It is the standard LZMA *properties* byte for the
/// default `lc=3, lp=0, pb=2` settings (`0x5D`), and serves as our sniff
/// signature on load. It cannot collide with plain JSON, which starts with
/// `{`, `[`, a quote, or ASCII whitespace — all distinct from `0x5D`.
///
/// We use the raw LZMA format rather than XZ because the pure-Rust `lzma-rs`
/// crate's XZ *encoder* stores data uncompressed, whereas its LZMA encoder
/// performs real LZ compression. Both decoders work; the LZMA path is the one
/// that actually shrinks the file.
pub const LZMA_MAGIC: u8 = 0x5D;

/// The kind of an object in the project tree (mirrors FlatCAM's `kind` strings).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ObjectKind {
    Gerber,
    Excellon,
    Geometry,
    CncJob,
    Svg,
    Document,
}

/// One object in the project.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProjectObject {
    pub name: String,
    pub kind: ObjectKind,
    /// Path to the source file this object was loaded from (if any).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_path: Option<String>,
    /// Free-form per-object options (the `obj_options` / `LoudDict` analogue).
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub options: BTreeMap<String, String>,
    /// Whether the object is shown on the canvas.
    #[serde(default = "default_true")]
    pub visible: bool,
    /// Name of the object this one was derived from (e.g. a CNCJob's source).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent: Option<String>,
}

fn default_true() -> bool {
    true
}

pub mod tree;
pub use tree::TreeRow;
pub mod naming;
pub mod relations;
pub mod properties;
pub use properties::properties;
pub mod ordering;
pub mod icons;
pub use icons::{kind_color, kind_icon, kind_label, kind_sort_index};
pub mod preferences;
pub use preferences::Preferences;

impl ProjectObject {
    pub fn new(name: impl Into<String>, kind: ObjectKind) -> Self {
        ProjectObject {
            name: name.into(),
            kind,
            source_path: None,
            options: BTreeMap::new(),
            visible: true,
            parent: None,
        }
    }

    pub fn with_source(mut self, path: impl Into<String>) -> Self {
        self.source_path = Some(path.into());
        self
    }

    pub fn set(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.options.insert(key.into(), value.into());
        self
    }
}

/// A FlatCAM project: an ordered collection of objects plus app-level settings.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Project {
    pub version: u32,
    /// Working units: "mm" or "in".
    pub units: String,
    pub objects: Vec<ProjectObject>,
    /// Name of the currently selected/active object, if any.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selected: Option<String>,
}

impl Default for Project {
    fn default() -> Self {
        Project {
            version: PROJECT_VERSION,
            units: "mm".into(),
            objects: Vec::new(),
            selected: None,
        }
    }
}

impl Project {
    pub fn new(units: impl Into<String>) -> Self {
        Project {
            version: PROJECT_VERSION,
            units: units.into(),
            objects: Vec::new(),
            selected: None,
        }
    }

    /// Add an object, returning an error if the name is already taken.
    pub fn add(&mut self, obj: ProjectObject) -> Result<(), AppError> {
        if self.objects.iter().any(|o| o.name == obj.name) {
            return Err(AppError::NotFound(format!("duplicate name: {}", obj.name)));
        }
        self.objects.push(obj);
        Ok(())
    }

    pub fn get(&self, name: &str) -> Option<&ProjectObject> {
        self.objects.iter().find(|o| o.name == name)
    }

    pub fn get_mut(&mut self, name: &str) -> Option<&mut ProjectObject> {
        self.objects.iter_mut().find(|o| o.name == name)
    }

    /// Remove an object by name; returns it, or an error if absent.
    pub fn remove(&mut self, name: &str) -> Result<ProjectObject, AppError> {
        let idx = self
            .objects
            .iter()
            .position(|o| o.name == name)
            .ok_or_else(|| AppError::NotFound(name.to_string()))?;
        Ok(self.objects.remove(idx))
    }

    pub fn objects_of(&self, kind: ObjectKind) -> impl Iterator<Item = &ProjectObject> {
        self.objects.iter().filter(move |o| o.kind == kind)
    }

    pub fn to_json(&self) -> Result<String, AppError> {
        Ok(serde_json::to_string_pretty(self)?)
    }

    pub fn from_json(s: &str) -> Result<Self, AppError> {
        Ok(serde_json::from_str(s)?)
    }

    pub fn save(&self, path: impl AsRef<Path>) -> Result<(), AppError> {
        std::fs::write(path, self.to_json()?)?;
        Ok(())
    }

    pub fn load(path: impl AsRef<Path>) -> Result<Self, AppError> {
        let text = std::fs::read_to_string(path)?;
        Self::from_json(&text)
    }

    // --- LZMA/XZ-compressed persistence -------------------------------------
    //
    // Project files are JSON, which compresses extremely well (the format is
    // repetitive: repeated keys, indentation, option strings). We serialize to
    // the same JSON as `to_json`, then wrap it in an XZ container. We picked the
    // pure-Rust `lzma-rs` crate for the codec so there is no dependency on a
    // system `liblzma` and it builds cleanly on Windows MSVC.

    /// Serialize this project to JSON and compress it into an LZMA container.
    /// The returned bytes begin with [`LZMA_MAGIC`].
    pub fn to_compressed_bytes(&self) -> Result<Vec<u8>, AppError> {
        let json = self.to_json()?;
        let mut out = Vec::new();
        lzma_rs::lzma_compress(&mut json.as_bytes(), &mut out)
            .map_err(|e| AppError::Compression(format!("lzma compress: {e}")))?;
        Ok(out)
    }

    /// Decode bytes that are *either* plain JSON or an LZMA-compressed project,
    /// auto-detecting which by sniffing the leading [`LZMA_MAGIC`] byte.
    pub fn from_bytes_auto(bytes: &[u8]) -> Result<Self, AppError> {
        if bytes.first() == Some(&LZMA_MAGIC) {
            let mut decompressed = Vec::new();
            let mut reader = bytes;
            lzma_rs::lzma_decompress(&mut reader, &mut decompressed)
                .map_err(|e| AppError::Compression(format!("lzma decompress: {e}")))?;
            let text = String::from_utf8(decompressed)
                .map_err(|e| AppError::Compression(format!("utf8: {e}")))?;
            Self::from_json(&text)
        } else {
            // Treat as plain JSON (skips a possible UTF-8 BOM defensively).
            let text = std::str::from_utf8(bytes)
                .map_err(|e| AppError::Compression(format!("utf8: {e}")))?;
            Self::from_json(text.trim_start_matches('\u{feff}'))
        }
    }

    /// Save this project as an XZ-compressed file.
    pub fn save_project_compressed(&self, path: impl AsRef<Path>) -> Result<(), AppError> {
        std::fs::write(path, self.to_compressed_bytes()?)?;
        Ok(())
    }

    /// Load a project from a file that is *either* plain JSON or XZ-compressed,
    /// auto-detecting the format. Complements the plain [`Project::load`].
    pub fn load_project_auto(path: impl AsRef<Path>) -> Result<Self, AppError> {
        let bytes = std::fs::read(path)?;
        Self::from_bytes_auto(&bytes)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> Project {
        let mut p = Project::new("mm");
        p.add(
            ProjectObject::new("top.gbr", ObjectKind::Gerber)
                .with_source("/tmp/top.gbr")
                .set("isolation_tool_dia", "0.4"),
        )
        .unwrap();
        p.add(ProjectObject::new("drills.drl", ObjectKind::Excellon)).unwrap();
        p
    }

    #[test]
    fn add_and_lookup() {
        let p = sample();
        assert_eq!(p.objects.len(), 2);
        assert_eq!(p.get("top.gbr").unwrap().kind, ObjectKind::Gerber);
        assert_eq!(p.objects_of(ObjectKind::Gerber).count(), 1);
    }

    #[test]
    fn duplicate_name_rejected() {
        let mut p = sample();
        assert!(p.add(ProjectObject::new("top.gbr", ObjectKind::Geometry)).is_err());
    }

    #[test]
    fn remove_object() {
        let mut p = sample();
        let removed = p.remove("drills.drl").unwrap();
        assert_eq!(removed.kind, ObjectKind::Excellon);
        assert!(p.get("drills.drl").is_none());
        assert!(p.remove("nope").is_err());
    }

    #[test]
    fn json_roundtrip() {
        let p = sample();
        let json = p.to_json().unwrap();
        let back = Project::from_json(&json).unwrap();
        assert_eq!(p, back);
        assert!(json.contains("\"version\": 1"));
        assert!(json.contains("isolation_tool_dia"));
    }

    #[test]
    fn options_preserved() {
        let p = sample();
        let back = Project::from_json(&p.to_json().unwrap()).unwrap();
        assert_eq!(
            back.get("top.gbr").unwrap().options.get("isolation_tool_dia"),
            Some(&"0.4".to_string())
        );
    }

    #[test]
    fn compressed_roundtrip_equals_project() {
        let p = sample();
        let bytes = p.to_compressed_bytes().unwrap();
        let back = Project::from_bytes_auto(&bytes).unwrap();
        assert_eq!(p, back);
    }

    #[test]
    fn compressed_bytes_carry_lzma_magic() {
        let p = sample();
        let bytes = p.to_compressed_bytes().unwrap();
        assert_eq!(bytes.first(), Some(&LZMA_MAGIC), "compressed blob must be LZMA");
    }

    #[test]
    fn auto_detect_handles_plain_json_and_compressed() {
        let p = sample();

        // Plain JSON blob.
        let json_bytes = p.to_json().unwrap().into_bytes();
        let from_json = Project::from_bytes_auto(&json_bytes).unwrap();
        assert_eq!(p, from_json);

        // Compressed blob.
        let comp_bytes = p.to_compressed_bytes().unwrap();
        let from_comp = Project::from_bytes_auto(&comp_bytes).unwrap();
        assert_eq!(p, from_comp);

        // Both paths yield the same project.
        assert_eq!(from_json, from_comp);
    }

    #[test]
    fn compression_shrinks_repetitive_project() {
        // A project with many similar objects compresses much smaller than its
        // JSON, because the JSON is highly repetitive.
        let mut p = Project::new("mm");
        for i in 0..200 {
            p.add(
                ProjectObject::new(format!("obj_{i:04}.gbr"), ObjectKind::Gerber)
                    .with_source("/tmp/repeated/source/path/file.gbr")
                    .set("isolation_tool_dia", "0.4")
                    .set("isolation_overlap", "0.15"),
            )
            .unwrap();
        }
        let json_len = p.to_json().unwrap().len();
        let comp_len = p.to_compressed_bytes().unwrap().len();
        assert!(
            comp_len < json_len,
            "compressed ({comp_len}) should be smaller than JSON ({json_len})"
        );
    }

    #[test]
    fn save_and_load_compressed_file_roundtrip() {
        let p = sample();
        let dir = std::env::temp_dir();
        let path = dir.join(format!("fc_app_test_{}.fcz", std::process::id()));

        p.save_project_compressed(&path).unwrap();
        // Auto-load must detect the compressed format.
        let back = Project::load_project_auto(&path).unwrap();
        assert_eq!(p, back);

        // Auto-load must also handle a plain-JSON file written by `save`.
        let json_path = dir.join(format!("fc_app_test_{}.json", std::process::id()));
        p.save(&json_path).unwrap();
        let back_json = Project::load_project_auto(&json_path).unwrap();
        assert_eq!(p, back_json);

        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_file(&json_path);
    }
}
